variables:

stages:
  - integration-test

variables:
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

before_script:
  - echo "Starting integration testing..."

integration_test:
  stage: integration-test
  script:
    - echo "Spinning up containers..."
    - docker-compose -f docker-compose.test.yml up -d
    - sleep 30 # This gives services time to boot, in theory won't be required as this will be done by container health checks
    - echo "Running InSpec tests..."
    - inspec exec tests/inspec
  # allow_failure: false

after_script:
  - echo "Testing complete."
