variables:

stages:
  - docker-compose
  - chef
  - inspec

cache: &global_cache
    key: $CI_PROJECT_NAME
    paths:
        - artifacts/

docker-compose:
  stage: docker-compose
  script:
    - docker-compose up -d --build
  when: manual
  artifacts: 
    when: always
    path: artifacts/logs

freeradius-chef:
  stage: chef
  script:
    - docker exec -d freeradius1 chef-client -j /path/to/node/file  -E freeradius
    - docker exec -d freeradius2 chef-client -j /path/to/node/file  -E freeradius
    - docker exec -d freeradius3 chef-client -j /path/to/node/file  -E freeradius

logstash-chef:
  stage: chef
  script:
    - docker exec -d logstash chef-client -j /path/to/node/file  -E logstash

kafka-chef:
  stage: chef
  script:
    - docker exec -d kafka-node-1 chef-client -j /path/to/node/file  -E kafka
    - docker exec -d kafka-node-2 chef-clienr -j /path/to/node/file -E kafka

elasticsearch-chef:
  stage: chef
  script:
    - docker exec -d elasticsearch chef-clienr -j /path/to/node/file -E elasticsearch

kibana-chef:
  stage: chef
  script:
    - docker exec -d kibana chef-clienr -j /path/to/node/file -E kibana

freeradius-inspec:
  stage: inspec
  script:
    - docker exec -d freeradius1 inspect exec /path/to/inspec/profile -b
    - docker exec -d freeradius2 inspect exec /path/to/inspec/profile -b
    - docker exec -d freeradius3 inspect exec /path/to/inspec/profile -b

logstash-inspec:
  stage: inspec
  script:
    - - docker exec -d logstash inspect exec /path/to/inspec/profile -b

kafka-inspec:
  stage: inspec
  script:
    - docker exec -d kafka-node-1 inspect exec /path/to/inspec/profile -b
    - docker exec -d kafka-node-2 inspect exec /path/to/inspec/profile -b

elasticsearch-inspec:
  stage: inspec
  script:
    - docker exec -d elasticsearch inspect exec /path/to/inspec/profile -b

kibana-inspec:
  stage: inspec
  script:
    - docker exec -d kibana inspect exec /path/to/inspec/profile -b