version: "3.8"

services:
  inspec:
    image: cincproject/workstation:${CINC_WORKSTATION_INSPEC_VERSION}
    container_name: inspec
    depends_on:
      - freeradius
    environment:
      - INSPEC_PROFILES_DIR=${INSPEC_PROFILES_DIR}
    volumes:
      - ${INSPEC_DIR}/exec.sh:/inspec/exec.sh
      - ${INSPEC_PROFILES_DIR}:/inspec/profiles
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      chmod +x /inspec/exec.sh &&
      /inspec/exec.sh
      "
