version: "2.4"

services:
  cinc-auditor:
    depends_on:
      - freeradius
    image: cincproject/workstation:${CINC_WORKSTATION_VERSION}
    container_name: cinc-auditor
    hostname: cinc-auditor
    volumes:
      - ./cinc-auditor/exec.sh:/cinc-auditor/exec.sh
      - ./cinc-auditor/profiles:/cinc-auditor/profiles
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      chmod +x /cinc-auditor/exec.sh &&
      /cinc-auditor/exec.sh
      "
