version: "2.4"

services:
  cinc-auditor:
    depends_on:
      - freeradius
    image: cincproject/workstation:${CINC_WORKSTATION_VERSION}
    container_name: cinc-auditor
    hostname: cinc-auditor
    volumes:
      - type: bind
        source: ./cinc-auditor/run_profiles.sh
        target: /cinc-auditor/run_profiles.sh
      - type: bind
        source: ./cinc-auditor/profiles
        target: /cinc-auditor/profiles
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      chmod +x /cinc-auditor/run_profiles.sh &&
      /cinc-auditor/run_profiles.sh
      "
