version: "3.8"

services:
  inspec:
    image: cincproject/workstation:${CINC_WORKSTATION_INSPEC_VERSION}
    container_name: inspec
    depends_on:
      - freeradius
    volumes:
      - ./inspec/exec.sh:/inspec/exec.sh
      - ./inspec/profiles:/inspec/profiles
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      chmod +x /inspec/exec.sh &&
      /inspec/exec.sh
      "
