version: "3.8"

networks:
  test_network:
    external: false

services:
  test_data:
    image: alpine:3.21.3
    container_name: test_data
    depends_on: 
      - freeradius
    volumes:
      - ./freeradius/sample_data/test_data.sh:/test_data/test_data.sh
      - freeradius_logs:${FREERADIUS_LOG_DIR}
    entrypoint: >
      sh -c "
      apk add --no-cache bash &&
      chmod +x /test_data/test_data.sh &&
      /test_data/test_data.sh
      "
    networks:
      - test_network

  inspec:
    image: cincproject/workstation:${CINC_WORKSTATION_INSPEC_VERSION}
    container_name: inspec
    depends_on:
      - freeradius
    volumes: 
      - ./elasticsearch/test/inspec:/share/elasticsearch
      - ./freeradius/test/inspec:/share/freeradius
      - ./kafka/test/inspec:/share/kafka
      - ./kibana/test/inspec:/share/kibana
      - ./logstash/test/inspec:/share/logstash
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c "
             inspec exec /share/freeradius --target docker://freeradius --no-create-lockfile &&
             inspec exec /share/logstash --target docker://logstash --no-create-lockfile &&
             inspec exec /share/kafka --target docker://kafka-1 --no-create-lockfile &&
             inspec exec /share/kafka --target docker://kafka-2 --no-create-lockfile &&
             inspec exec /share/kafka --target docker://kafka-3 --no-create-lockfile &&
             inspec exec /share/elasticsearch --target docker://elasticsearch --no-create-lockfile &&
             inspec exec /share/kibana --target docker://kibana --no-create-lockfile &&
             echo "All tests passed! Gracefully stopping containers..."
            "
    networks:
      - test_network
