version: "3.8"

services:
  inspec:
    image: cincproject/workstation:${CINC_WORKSTATION_INSPEC_VERSION}
    container_name: inspec
    depends_on:
      - freeradius
    volumes:
      - ./inspec/exec.sh:/inspec/exec.sh
      - ${ELASTICSEARCH_INSPEC_DIR}:/share/elasticsearch
      - ${FREERADIUS_INSPEC_DIR}:/share/freeradius
      - ${KAFKA_INSPEC_DIR}:/share/kafka
      - ${KIBANA_INSPEC_DIR}:/share/kibana
      - ${LOGSTASH_INSPEC_DIR}:/share/logstash
      - ${FILEBEAT_INSPEC_DIR}:/share/filebeat
      - ${METRICBEAT_INSPEC_DIR}:/share/metricbeat
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      chmod +x /inspec/exec.sh &&
      /inspec/exec.sh
      "
