packer {
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
    inspec = {
      version = ">= 0.0.1"
      source  = "github.com/hashicorp/inspec"
    }
  }
}

variable "accelerator" {
  type    = string
  default = "hvf"
}

variable "base_image" {
  type    = string
  default = "./artifacts/ubuntu-base.qcow2"
}

variable "cpu" {
  type    = string
  default = "max"
}

variable "disk_size" {
  type    = string
  default = "82432"
}

variable "display" {
  type    = string
  default = "cocoa"
}

variable "headless" {
  type    = string
  default = "true"
}

variable "memory" {
  type    = string
  default = "4096"
}

variable "user" {
  type    = string
  default = "sys_user"
}

variable "password" {
  type    = string
  default = "password"
}

variable "smp" {
  type    = string
  default = "8"
}

variable "vm_name" {
  type    = string
  default = "ubuntu-build.qcow2"
}

source "qemu" "autogenerated_1" {
  accelerator               = "${var.accelerator}"
  boot_command              = ["<enter><wait>"]
  boot_wait                 = "2s"
  cpus                      = "${var.smp}"
  disk_compression          = true
  disk_image                = true
  disk_interface            = "ide"
  disk_size                 = "${var.disk_size}"
  format                    = "qcow2"
  headless                  = "${var.headless}"
  host_port_max             = 2229
  host_port_min             = 2222
  http_directory            = "./"
  http_port_max             = 10089
  http_port_min             = 10082
  iso_checksum              = "none"
  iso_url                   = "${var.base_image}"
  memory                    = "${var.memory}"
  net_device                = "virtio-net"
  output_directory          = "./build-${local.timestamp}"
  qemuargs                  = [["-cpu", "${var.cpu}"], ["-display", "${var.display}"], ["-m", "${var.memory}"], ["-serial", "stdio"]]
  shutdown_command          = "sudo shutdown -P now"
  ssh_clear_authorized_keys = true
  ssh_password              = "${var.password}"
  ssh_port                  = 22
  ssh_timeout               = "15m"
  ssh_username              = "${var.user}"
  vm_name                   = "${var.vm_name}"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "inspec" {
    extra_arguments = ["--sudo", "--sudo-password=password"]
    inspec_env_vars = ["CHEF_LICENSE=accept"]
    profile         = "tests"
    user            = "sys_user"
  }
}