http.host: 0.0.0.0
log.format: plain
log.level: info
pipeline.separate_logs: true
xpack.monitoring.elasticsearch.hosts:
- https://elasticsearch:9200
xpack.monitoring.enabled: ${xpack.monitoring.enabled}
