http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
# path.data: /usr/share/logstash/data
# path.logs: /usr/share/logstash/logs
# path.config: /usr/share/logstash/config
pipeline.separate_logs: true
log.level: info
log.format: plain
