elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.ssl.verificationMode: none

# Disable xpack security completely if you're not using it
# xpack.security.enabled: false
# xpack.security.ssl.verificationMode: none

server.name: kibana
server.host: "0.0.0.0"

# Default locale
i18n.locale: "en"

# Logging
logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: json
  root:
    appenders: [default, file]
